In [1]:
##Calculating Piotroski's F score
import numpy as np
import pandas as pd
from tabula import read_pdf as rp
from bs4 import BeautifulSoup as bs
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import os
import time

In [37]:
## setting up browser ##returns driver
def browser_setup():
    url="https://www.moneycontrol.com/stocksmarketsindia/"
    chrome_options = Options();
    chrome_options.add_argument('--window-size=1920,1080');
    chrome_options.add_argument('--blink-settings=imagesEnabled=false')
    chrome_options.add_argument("--headless")
    chrome_options.binary_location = 'C:/Users/Harshit Mishra/AppData/Local/Google/Chrome SxS/Application/chrome.exe'    
    driver = webdriver.Chrome(executable_path=os.path.abspath("chromedriver"),options=chrome_options)  
    driver.get(url)
    driver.implicitly_wait(5)
    print("driver loaded")
    return driver

In [3]:
##Loading excel to connect security ticker to bse code
def sec_id(security_ticker):
    sheet=pd.read_csv("Equity.csv");
    row=sheet[sheet["Security Id"]==security_ticker]
    if(row.shape[0]==0):
        code = "Invalid Ticker"
    else:
        code = row.iloc[0,0];
    return code;

In [31]:
#to put security's bse code in search bar and open its page
def gotosecurity(code,driver):
    search_bar = driver.find_element_by_xpath('/html/body/header/div[1]/div/div[2]/div[2]/div[1]/div/form/input[5]')
    search_bar.clear()
    if(code=="Invalid Ticker"): 
        print(code);
    else:
        search_bar.send_keys(str(code));
        go = driver.find_element_by_xpath('/html/body/header/div[1]/div/div[2]/div[2]/div[1]/a')
        go.click();
        time.sleep(5);
        print("Opened security page")

In [5]:
##get links to financial statements
def getlinks(driver):
    financials=driver.find_element_by_xpath('//*[@id="sec_quotes"]/div[2]/div/div[1]/div[3]/div/div/nav/div/ul/li[8]/a')
    financials.click();
    time.sleep(5);
    bs= driver.find_element_by_xpath('//*[@id="sec_quotes"]/div[2]/div/div[1]/div[3]/div/div/nav/div/ul/li[8]/ul/li[1]/a')
    bs_link=bs.get_attribute("href");
    pnl= driver.find_element_by_xpath('//*[@id="sec_quotes"]/div[2]/div/div[1]/div[3]/div/div/nav/div/ul/li[8]/ul/li[2]/a')
    pnl_link = pnl.get_attribute("href");
    cf= driver.find_element_by_xpath('//*[@id="sec_quotes"]/div[2]/div/div[1]/div[3]/div/div/nav/div/ul/li[8]/ul/li[7]/a')
    cf_link = cf.get_attribute("href")
    yr= driver.find_element_by_xpath('//*[@id="sec_quotes"]/div[2]/div/div[1]/div[3]/div/div/nav/div/ul/li[8]/ul/li[6]/a')
    yr_link = yr.get_attribute("href")
    statement_links = [bs_link,pnl_link,cf_link,yr_link];
    return statement_links;

In [6]:
def getbs(driver,bs_link):
    driver.get(bs_link);
    time.sleep(5);
    values=pd.DataFrame();
    for body in driver.find_elements_by_xpath('//*[@id="standalone-new"]/div[1]/table/tbody'):
            for r in body.find_elements_by_xpath('./tr'):
                val=pd.DataFrame();
                for data in r.find_elements_by_xpath('./td'):
                    val=val.append([data.get_attribute('textContent')],ignore_index=True);
                values=values.append(val.T,ignore_index=True)
    return values

In [7]:
def getpnl(driver,pnl_link):
    driver.get(pnl_link);
    time.sleep(5);
    values=pd.DataFrame();
    for body in driver.find_elements_by_xpath('//*[@id="standalone-new"]/div[1]/table/tbody'):
            for r in body.find_elements_by_xpath('./tr'):
                val=pd.DataFrame();
                for data in r.find_elements_by_xpath('./td'):
                    val=val.append([data.get_attribute('textContent')],ignore_index=True);
                values=values.append(val.T,ignore_index=True)
    return values

In [8]:
def getcf(driver,cf_link):
    driver.get(cf_link);
    time.sleep(5);
    values=pd.DataFrame();
    for body in driver.find_elements_by_xpath('//*[@id="standalone-new"]/div[1]/table/tbody'):
            for r in body.find_elements_by_xpath('./tr'):
                val=pd.DataFrame();
                for data in r.find_elements_by_xpath('./td'):
                    val=val.append([data.get_attribute('textContent')],ignore_index=True);
                values=values.append(val.T,ignore_index=True)
    return values

In [9]:
def getyr(driver,yr_link):
    driver.get(yr_link);
    time.sleep(5);
    values=pd.DataFrame();
    for body in driver.find_elements_by_xpath('//*[@id="standalone-new"]/div[1]/table/tbody'):
            for r in body.find_elements_by_xpath('./tr'):
                val=pd.DataFrame();
                for data in r.find_elements_by_xpath('./td'):
                    val=val.append([data.get_attribute('textContent')],ignore_index=True);
                values=values.append(val.T,ignore_index=True)
    for i in range(values.shape[0]):
        for j in reversed(range(values.shape[1]-1)):
            if(values.iloc[i,j]=="--"):
                values.iloc[i,j]=values.iloc[i,j+1]
    return values

In [10]:
def get_statements(security_ticker):
    security_ticker=security_ticker.upper()
    driver=browser_setup();
    code = sec_id(security_ticker);
    gotosecurity(code,driver); #Opens security page in driver
    statement_links=getlinks(driver);
    bs=getbs(driver,statement_links[0]);
    pnl=getpnl(driver,statement_links[1]);
    cf= getcf(driver,statement_links[2]);
    yr = getyr(driver,statement_links[3]);
##remove repeated column from financial statements ## exists in case of multiple data/filings for latest year
    for i in reversed(range(1,bs.shape[1])):
        if(bs.iloc[0,i]==bs.iloc[0,i-1]):
            bs.loc[bs[i-1]=="0.00",i-1]=bs[bs[i-1]=="0.00"][i]
            bs=bs.drop(labels=i,axis=1);
            bs.columns=range(bs.shape[1]);
    
    for i in reversed(range(1,pnl.shape[1])):
        if(pnl.iloc[0,i]==pnl.iloc[0,i-1]):
            pnl.loc[pnl[i-1]=="0.00",i-1]=pnl[pnl[i-1]=="0.00"][i]
            pnl=pnl.drop(labels=i,axis=1);
            pnl.columns=range(pnl.shape[1]);
    
    for i in reversed(range(1,cf.shape[1])):
        if(cf.iloc[0,i]==cf.iloc[0,i-1]):
            cf.loc[cf[i-1]=="0.00",i-1]=cf[cf[i-1]=="0.00"][i]
            cf=cf.drop(labels=i,axis=1);
            cf.columns=range(cf.shape[1]);
            
    for i in reversed(range(1,yr.shape[1])):
        if(yr.iloc[0,i]==yr.iloc[0,i-1]):
            yr.loc[yr[i-1]=="0.00",i-1]=yr[yr[i-1]=="0.00"][i]
            yr=yr.drop(labels=i,axis=1);
            yr.columns=range(yr.shape[1]);
    statements=[bs,pnl,cf,yr];
    return statements;

In [38]:
statements=get_statements("yesbank")
bs=statements[0];
pnl=statements[1];
cf= statements[2];
yr = statements[3];

driver loaded

In [39]:
bs

,0,1,2,3,4
0,Balance Sheet of Yes Bank (in Rs. Cr.),Mar 19,Mar 18,Mar 17,
1,,12 mths,12 mths,12 mths,
2,EQUITIES AND LIABILITIES,,,,
3,SHAREHOLDER'S FUNDS,,,,
4,Equity Share Capital,463.01,460.59,456.49,
5,Total Share Capital,463.01,460.59,456.49,
6,Revaluation Reserve,0.00,0.00,0.00,
7,Reserves and Surplus,"26,441.19","25,297.69","21,597.57",
8,Total Reserves and Surplus,"26,441.19","25,297.69","21,597.57",
9,Total ShareHolders Funds,"26,904.20","25,758.28","22,054.06",
10,Deposits,"227,610.18","200,738.15","142,873.86",
11,Borrowings,"108,424.11","74,893.58","38,606.67",
12,Other Liabilities and Provisions,"17,887.68","11,055.60","11,525.33",
13,Total Capital and Liabilities,"380,826.17","312,445.60","215,059.92",
14,ASSETS,,,,
15,Cash and Balances with Reserve Bank of India,"10,797.74","11,425.75","6,952.07",
16,Balances with Banks Money at Call and Short No...,"16,091.77","13,308.62","12,597.37",
17,Investments,"89,522.03","68,398.94","50,031.80",
18,Advances,"241,499.60","203,533.86","132,262.68",
19,Fixed Assets,817.00,832.39,683.54,
20,Other Assets,"22,098.02","14,946.04","12,532.46",
21,Total Assets,"380,826.17","312,445.60","215,059.92",
22,OTHER ADDITIONAL INFORMATION,,,,
23,Number of Branches,"1,120.00","1,100.00","1,000.00",
24,Number of Employees,"21,136.00","18,238.00","20,125.00",
25,Capital Adequacy Ratios (%),17.00,18.00,17.00,
26,KEY PERFORMANCE INDICATORS,,,,
27,Tier 1 (%),11.00,13.00,13.00,
28,Tier 2 (%),5.00,5.00,4.00,
29,ASSETS QUALITY,,,,
30,Gross NPA,"7,882.56","2,626.80","2,018.56",
31,Gross NPA (%),3.00,1.00,2.00,
32,Net NPA,"4,484.85","1,312.75","1,072.27",
33,Net NPA (%),2.00,1.00,1.00,
34,Net NPA To Advances (%),2.00,1.00,1.00,
35,"CONTINGENT LIABILITIES, COMMITMENTS",,,,
36,Bills for Collection,"5,059.24","1,935.56","1,390.00",
37,Contingent Liabilities,"654,158.02","581,829.64","379,564.16",

In [411]:
##Defining required variables for Pietroskei ratios
def pet_rat(bs,pnl,cf):
    TA_0=float(bs[bs[0]=="Total Assets"].iloc[0,1].replace(',','')) ##Total Assets
    TA_1=float(bs[bs[0]=="Total Assets"].iloc[0,2].replace(',','')) ##Previous Year's Total Assets
    TA_2=float(bs[bs[0]=="Total Assets"].iloc[0,3].replace(',','')) ##Previous to Previous Year's Total Assets
    NI_0=float(pnl[pnl[0].isin(["Profit/Loss For The Period","Net Profit / Loss for The Year"])].iloc[0,1].replace(',','')) ##Net income
    NI_1=float(pnl[pnl[0].isin(["Profit/Loss For The Period","Net Profit / Loss for The Year"])].iloc[0,2].replace(',','')) ##Previous Year's Total Assets
#average total assets
    avg_ta_0 = np.mean([TA_0,TA_1]);
    avg_ta_1 = np.mean([TA_1,TA_2]);
#Operating Cash flow
    ocf = float(cf[cf[0]=="Net CashFlow From Operating Activities"].iloc[0,1].replace(',','')) 
#Long term debt
    ltd_0 = float(bs[bs[0].isin(["Long Term Borrowings","Borrowings"])].iloc[0,1].replace(',',''))
    ltd_1 = float(bs[bs[0].isin(["Long Term Borrowings","Borrowings"])].iloc[0,2].replace(',',''))

#liquidity
#current assets for banks and other firms
    if("Cash and Balances with Reserve Bank of India" in bs[0].values):
        cb_with_rbi_0 = float(bs[bs[0]=="Cash and Balances with Reserve Bank of India"].iloc[0,1].replace(',',''));
        cb_with_rbi_1 = float(bs[bs[0]=="Cash and Balances with Reserve Bank of India"].iloc[0,2].replace(',',''));
        bal_with_banks_0=float(bs[bs[0]=="Balances with Banks Money at Call and Short Notice"].iloc[0,1].replace(',',''));
        bal_with_banks_1=float(bs[bs[0]=="Balances with Banks Money at Call and Short Notice"].iloc[0,2].replace(',',''));
        investments_0= float(bs[bs[0]=="Investments"].iloc[0,1].replace(',',''));
        investments_1= float(bs[bs[0]=="Investments"].iloc[0,2].replace(',',''));
        advances_0 = float(bs[bs[0]=="Advances"].iloc[0,1].replace(',',''));
        advances_1 = float(bs[bs[0]=="Advances"].iloc[0,2].replace(',',''));
        curr_ass_0 = cb_with_rbi_0 + bal_with_banks_0 + investments_0 + advances_0;
        curr_ass_1 = cb_with_rbi_1 + bal_with_banks_1 + investments_1 + advances_1;
    ##taking borrwings as short term borrowings for banks
        deposits_0 =   float(bs[bs[0]=="Deposits"].iloc[0,1].replace(',',''));
        deposits_1 =   float(bs[bs[0]=="Deposits"].iloc[0,2].replace(',',''));
        borrowings_0 = ltd_0;
        borrowings_1 = ltd_1;
        ltd_0=0;
        ltd_1=0;
        curr_liab_0 = deposits_0+borrowings_0;
        curr_liab_1 = deposits_1+borrowings_1;
    else:
        curr_ass_0 = float(bs[bs[0]=="Total Current Assets"].iloc[0,1].replace(',',''));
        curr_ass_1 = float(bs[bs[0]=="Total Current Assets"].iloc[0,2].replace(',',''));
        curr_liab_0 = float(bs[bs[0]=="Total Current Liabilities"].iloc[0,1].replace(',',''));
        curr_liab_1 = float(bs[bs[0]=="Total Current Liabilities"].iloc[0,2].replace(',',''));

In [ ]:
##Calculating Petroski's ratios
# 1) Profitability ratis
#roa
def petroski_ratios():
    roa_0=NI_0/TA_1;
    roa_1=NI_1/TA_2;
#cfra = Net cash flow from operating activities/Total Assets from the beginning of the year
    cfra = ocf/TA_1
#delta roa
    del_roa=roa_0-roa_1;
#accurals net cash flow - net operating income/Total assets from the beginning of the year
    accurals = cfra-roa_0;
# 2) Capital Structure Measures
#delta leverage
    lev_0 = ltd_0/avg_ta_0;
    lev_1 = ltd_1/avg_ta_1;
    del_lev = ltd_0-ltd_1;
# delta liquidity
    liquidity_0 = current_ass_0/curr_liab_0;
    liquidity_1 = current_ass_1/curr_liab_1;
    del_liq = liquidity_0 - liquidity_1;
#del_share_issue
# get from yearly results

In [318]:
#df.loc[df.B == 0, 'B'] = df.A.shift(-1)
#cf[cf[1]=="0.00"]
cf.loc[cf[1]=="0.00",1]=cf[cf[1]=="0.00"][2]

In [385]:
#driver=browser_setup()
pnl= getpnl(driver,"https://www.moneycontrol.com/financials/relianceindustries/profit-lossVI/RI#RI");

In [430]:

    print("hh")

hh

In [429]:
"Cash and Balances with Reserve Bank of India" in (bs)

False